version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social_networking_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/social_networking
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  pgdata:
